import React from 'react';
import ReactDOM from 'react-dom';
import Amplify from 'aws-amplify';
//import awsconfig from './aws-exports'; // This file will be auto-generated by Amplify
import App from './App';

Amplify.configure(awsconfig);

ReactDOM.render(<App />, document.getElementById('root'));
